title: "PMVC: Data Augmentation-Based Prosody Modeling for Expressive Voice Conversion"
description: https://largeaudiomodel.com

theme: jekyll-theme-cayman

github:
  repository_url: https://largeaudiomodel.com/
